export const DATA_AUTOS = [
  { mes:"Enero",      fecha:"01/01", efemeride:"Año Nuevo",                           categoria:"NAC",  idea:"Feliz 2026 🎉 Este año estrenamos juntos. ¿Cuál es tu próximo auto?" },
  { mes:"Enero",      fecha:"06/01", efemeride:"Día de Reyes",                        categoria:"MKT",  idea:"Los Reyes Magos traen el mejor regalo: llaves de un 0km 🎁" },
  { mes:"Enero",      fecha:"12/01", efemeride:"Día Mundial del Auto Eléctrico",      categoria:"AUTO", idea:"El futuro ya llegó 🔋⚡ Conocé nuestra línea de autos eléctricos e híbridos" },
  { mes:"Enero",      fecha:"30/01", efemeride:"Día de la Conducción Segura",         categoria:"AUTO", idea:"Manejar con cuidado es el mejor equipamiento 🛡️ #ManejoSeguro" },
  { mes:"Febrero",    fecha:"14/02", efemeride:"San Valentín",                        categoria:"MKT",  idea:"Una prueba de manejo para dos 💘 Vení con quien más querés" },
  { mes:"Marzo",      fecha:"08/03", efemeride:"Día Internacional de la Mujer",       categoria:"MKT",  idea:"Mujeres al volante, fuerza y libertad 🏁 #MujeresQueManeja" },
  { mes:"Marzo",      fecha:"24/03", efemeride:"Día Nacional de la Memoria",          categoria:"NAC",  idea:"Un día para recordar y reflexionar 🕊️" },
  { mes:"Marzo",      fecha:"25/03", efemeride:"Día del Auto Clásico",                categoria:"AUTO", idea:"Historia sobre ruedas 🏆 ¿Cuál es tu auto clásico favorito?" },
  { mes:"Marzo",      fecha:"26/03", efemeride:"Día del Combatiente de Malvinas",     categoria:"NAC",  idea:"En honor a quienes defendieron nuestra patria 🇦🇷" },
  { mes:"Abril",      fecha:"02/04", efemeride:"Día de los Caídos en Malvinas",       categoria:"NAC",  idea:"Los recordamos con orgullo y respeto 🇦🇷" },
  { mes:"Abril",      fecha:"06/04", efemeride:"Día del Deporte del Motor",           categoria:"AUTO", idea:"La adrenalina de la velocidad 🏎️ ¿Cuál es tu carrera favorita?" },
  { mes:"Abril",      fecha:"22/04", efemeride:"Día de la Tierra",                    categoria:"MKT",  idea:"Autos más eficientes para un planeta más sano 🌱 #SustentabilidadJack" },
  { mes:"Mayo",       fecha:"01/05", efemeride:"Día del Trabajador",                  categoria:"NAC",  idea:"A todos los que mueven el país cada día, gracias 🙌" },
  { mes:"Mayo",       fecha:"15/05", efemeride:"Día de la Familia",                   categoria:"MKT",  idea:"Cada familia tiene su auto ideal 👨‍👩‍👧‍👦 Encontrá el tuyo en Grupo Jack" },
  { mes:"Mayo",       fecha:"25/05", efemeride:"Revolución de Mayo",                  categoria:"NAC",  idea:"¡Feliz 25 de Mayo! 🇦🇷 Patria al volante, siempre adelante" },
  { mes:"Junio",      fecha:"15/06", efemeride:"Día del Padre",                       categoria:"MKT",  idea:"El mejor regalo para papá tiene cuatro ruedas 🎁🚗" },
  { mes:"Junio",      fecha:"20/06", efemeride:"Día de la Bandera",                   categoria:"NAC",  idea:"Feliz Día de la Bandera 🇦🇷 Orgullosos de ser argentinos" },
  { mes:"Junio",      fecha:"21/06", efemeride:"Inicio del Invierno",                 categoria:"AUTO", idea:"¿Tu auto está listo para el frío? 🧊 Tips de mantenimiento de invierno" },
  { mes:"Junio",      fecha:"26/06", efemeride:"Hot Sale",                            categoria:"MKT",  idea:"Las mejores ofertas del año en autos 🔥 #HotSale2026 #GrupoJack" },
  { mes:"Julio",      fecha:"09/07", efemeride:"Día de la Independencia",             categoria:"NAC",  idea:"¡Feliz 9 de Julio! Libertad sobre cuatro ruedas 🇦🇷" },
  { mes:"Julio",      fecha:"18/07", efemeride:"Vacaciones de Invierno",              categoria:"MKT",  idea:"¿A dónde vas estas vacaciones? El auto perfecto te espera 🗺️" },
  { mes:"Agosto",     fecha:"17/08", efemeride:"Paso a la Inmortalidad — San Martín", categoria:"NAC",  idea:"En honor al Libertador 🇦🇷 San Martín, siempre presente" },
  { mes:"Agosto",     fecha:"01/08", efemeride:"Día del Niño",                        categoria:"MKT",  idea:"Los chicos también sueñan con autos 🚗✨" },
  { mes:"Septiembre", fecha:"21/09", efemeride:"Día de la Primavera",                 categoria:"MKT",  idea:"¡Bienvenida primavera! 🌸 La estación perfecta para estrenar tu nuevo auto" },
  { mes:"Septiembre", fecha:"25/09", efemeride:"Día Mundial del Turismo",             categoria:"MKT",  idea:"Viajar es vivir 🗺️ ¿Con qué auto recorrés Argentina?" },
  { mes:"Octubre",    fecha:"12/10", efemeride:"Día de la Diversidad Cultural",       categoria:"NAC",  idea:"Diversidad en cada camino 🌍 Todos los caminos llevan a Grupo Jack" },
  { mes:"Octubre",    fecha:"16/10", efemeride:"Cyber Monday",                        categoria:"MKT",  idea:"Ofertas digitales en autos 0km ⚡💻 #CyberMonday2026" },
  { mes:"Noviembre",  fecha:"20/11", efemeride:"Día de la Soberanía Nacional",        categoria:"NAC",  idea:"Soberanía y orgullo argentino 🇦🇷 #20deNoviembre" },
  { mes:"Noviembre",  fecha:"30/11", efemeride:"Black Friday",                        categoria:"MKT",  idea:"Ofertas de fin de año en autos 🛍️ #BlackFriday2026 #GrupoJack" },
  { mes:"Diciembre",  fecha:"18/12", efemeride:"Día de la Seguridad Vial",            categoria:"AUTO", idea:"Manejá con responsabilidad 🚦 Un compromiso de todos en la ruta" },
  { mes:"Diciembre",  fecha:"24/12", efemeride:"Nochebuena",                          categoria:"MKT",  idea:"¡Felices Fiestas! Que la magia de la Navidad te acompañe en cada viaje 🎄" },
  { mes:"Diciembre",  fecha:"25/12", efemeride:"Navidad",                             categoria:"NAC",  idea:"¡Feliz Navidad de parte de todo Grupo Jack! 🎁🚗" },
  { mes:"Diciembre",  fecha:"31/12", efemeride:"Nochevieja",                          categoria:"MKT",  idea:"Cerramos 2026 con el tanque lleno 🥂🎊 ¡Hasta el año que viene!" },
]

export const DATA_MOTOS = [
  { mes:"Enero",      fecha:"01/01", efemeride:"Año Nuevo",                           categoria:"NAC",  idea:"¡Feliz 2026! 🎉 Este año la ruta nos espera. ¿Cuántos km vas a hacer?" },
  { mes:"Enero",      fecha:"06/01", efemeride:"Día de Reyes",                        categoria:"MKT",  idea:"Los Reyes Magos también traen motos 🏍️🎁 ¿Pediste la tuya?" },
  { mes:"Enero",      fecha:"17/01", efemeride:"Día del Amigo (Cono Sur)",            categoria:"MKT",  idea:"Nada une más que salir en moto con los amigos 🤝🏍️" },
  { mes:"Enero",      fecha:"30/01", efemeride:"Día de la Conducción Segura",         categoria:"MOTO", idea:"Casco, guantes, chaqueta: el equipamiento que salva vidas 🛡️ #MotoSegura" },
  { mes:"Febrero",    fecha:"14/02", efemeride:"San Valentín",                        categoria:"MKT",  idea:"Dos en moto, la escapada perfecta 💘 ¿Ya planearon el próximo viaje?" },
  { mes:"Febrero",    fecha:"01/02", efemeride:"Inicio de temporada de motos",        categoria:"MOTO", idea:"¡Arrancó la temporada! 🏁 Preparate para rodar todo el año con nosotros" },
  { mes:"Marzo",      fecha:"08/03", efemeride:"Día Internacional de la Mujer",       categoria:"MKT",  idea:"Las motociclistas también hacen historia 🏍️✊ #MujeresMoto" },
  { mes:"Marzo",      fecha:"24/03", efemeride:"Día Nacional de la Memoria",          categoria:"NAC",  idea:"Un día para recordar y reflexionar 🕊️" },
  { mes:"Marzo",      fecha:"26/03", efemeride:"Día del Combatiente de Malvinas",     categoria:"NAC",  idea:"En honor a quienes defendieron nuestra patria 🇦🇷" },
  { mes:"Abril",      fecha:"02/04", efemeride:"Día de los Caídos en Malvinas",       categoria:"NAC",  idea:"Los recordamos con orgullo y respeto 🇦🇷" },
  { mes:"Abril",      fecha:"06/04", efemeride:"Día del Deporte del Motor",           categoria:"MOTO", idea:"Del MotoGP al enduro: velocidad sobre dos ruedas 🏍️" },
  { mes:"Abril",      fecha:"22/04", efemeride:"Día de la Tierra",                    categoria:"MKT",  idea:"Las motos, una opción más eficiente para moverse 🌱 #EcoMoto" },
  { mes:"Mayo",       fecha:"01/05", efemeride:"Día del Trabajador",                  categoria:"NAC",  idea:"A los que usan la moto para llegar al trabajo cada día, gracias 🙌" },
  { mes:"Mayo",       fecha:"21/05", efemeride:"Día de la Movilidad Urbana",          categoria:"MOTO", idea:"La moto: la solución al tráfico urbano 🏍️🌆" },
  { mes:"Mayo",       fecha:"25/05", efemeride:"Revolución de Mayo",                  categoria:"NAC",  idea:"¡Feliz 25 de Mayo! 🇦🇷 Libres y sobre dos ruedas" },
  { mes:"Junio",      fecha:"15/06", efemeride:"Día del Padre",                       categoria:"MKT",  idea:"¿Tu papá es motoquero? El regalo perfecto tiene dos ruedas 🎁🏍️" },
  { mes:"Junio",      fecha:"20/06", efemeride:"Día de la Bandera",                   categoria:"NAC",  idea:"Feliz Día de la Bandera 🇦🇷 Rodamos con orgullo argentino" },
  { mes:"Junio",      fecha:"21/06", efemeride:"Inicio del Invierno",                 categoria:"MOTO", idea:"Consejos para rodar seguro en invierno 🧊🏍️ Revisá neumáticos y frenos" },
  { mes:"Junio",      fecha:"26/06", efemeride:"Hot Sale",                            categoria:"MKT",  idea:"Las mejores ofertas del año en motos 🔥🏍️ #HotSale2026" },
  { mes:"Julio",      fecha:"09/07", efemeride:"Día de la Independencia",             categoria:"NAC",  idea:"Libertad sobre dos ruedas 🇦🇷🏍️ ¡Feliz 9 de Julio!" },
  { mes:"Julio",      fecha:"15/07", efemeride:"Día Mundial de la Moto",              categoria:"MOTO", idea:"¡Feliz Día de la Moto! 🏍️🔥 ¿Cuántos km llevan este año?" },
  { mes:"Julio",      fecha:"18/07", efemeride:"Vacaciones de Invierno",              categoria:"MKT",  idea:"¿Vacaciones en moto? La aventura más libre que existe 🗺️🏍️" },
  { mes:"Agosto",     fecha:"17/08", efemeride:"Paso a la Inmortalidad — San Martín", categoria:"NAC",  idea:"En honor al Libertador 🇦🇷 Rodamos con su memoria" },
  { mes:"Agosto",     fecha:"22/08", efemeride:"Día Mundial del Motociclismo",        categoria:"MOTO", idea:"Hoy celebramos la pasión por los dos ruedas 🏍️🌍 ¡Compartí tu foto!" },
  { mes:"Agosto",     fecha:"01/08", efemeride:"Día del Niño",                        categoria:"MKT",  idea:"Los futuros motociclistas crecen soñando con dos ruedas 🏍️✨" },
  { mes:"Septiembre", fecha:"11/09", efemeride:"Día del Maestro",                     categoria:"MKT",  idea:"Gracias a quienes nos enseñaron a amar la ruta 🍎🏍️" },
  { mes:"Septiembre", fecha:"21/09", efemeride:"Día de la Primavera",                 categoria:"MKT",  idea:"¡Llegó la primavera! 🌸🏍️ La mejor época para rodar" },
  { mes:"Septiembre", fecha:"15/09", efemeride:"Semana de la Seguridad Vial en Moto", categoria:"MOTO", idea:"Esta semana recordamos: el casco no es opcional 🪖 #MotoConsciente" },
  { mes:"Octubre",    fecha:"12/10", efemeride:"Día de la Diversidad Cultural",       categoria:"NAC",  idea:"Motociclistas de todas las culturas, un solo camino 🌍🏍️" },
  { mes:"Octubre",    fecha:"16/10", efemeride:"Cyber Monday",                        categoria:"MKT",  idea:"Ofertas en motos y accesorios online ⚡🏍️ #CyberMonday2026" },
  { mes:"Octubre",    fecha:"20/10", efemeride:"Día del Motociclista Argentino",      categoria:"MOTO", idea:"¡Feliz Día del Motociclista! 🏍️🇦🇷 Celebramos a toda la comunidad moto" },
  { mes:"Noviembre",  fecha:"20/11", efemeride:"Día de la Soberanía Nacional",        categoria:"NAC",  idea:"Soberanía y orgullo argentino sobre dos ruedas 🇦🇷🏍️" },
  { mes:"Noviembre",  fecha:"28/11", efemeride:"Día del Mecánico",                    categoria:"MOTO", idea:"A los que mantienen nuestras motos en ruta: ¡gracias! 🔧🏍️" },
  { mes:"Noviembre",  fecha:"30/11", efemeride:"Black Friday",                        categoria:"MKT",  idea:"Ofertas de fin de año en motos 🛍️🏍️ #BlackFriday2026" },
  { mes:"Diciembre",  fecha:"08/12", efemeride:"Inmaculada Concepción",               categoria:"NAC",  idea:"Feriado largo 🕊️ ¿Ya armaste la escapada en moto?" },
  { mes:"Diciembre",  fecha:"18/12", efemeride:"Día de la Seguridad Vial",            categoria:"MOTO", idea:"Rodar seguro es la mejor forma de llegar siempre 🚦🏍️ #MotoSegura" },
  { mes:"Diciembre",  fecha:"24/12", efemeride:"Nochebuena",                          categoria:"MKT",  idea:"¡Felices Fiestas moteros! Que el camino siempre sea libre 🎄🏍️" },
  { mes:"Diciembre",  fecha:"25/12", efemeride:"Navidad",                             categoria:"NAC",  idea:"¡Feliz Navidad! 🎁🏍️ Los mejores kilómetros están por venir" },
  { mes:"Diciembre",  fecha:"31/12", efemeride:"Nochevieja",                          categoria:"MKT",  idea:"Cerramos 2026 con el motor encendido 🥂🏍️🎊 ¡Hasta el año que viene!" },
]
